// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_P0mvuXcsfLyMGYBslX0jzMT2O5vCxUo',
    appId: '1:319505449606:web:aa2922b519691a526dc707',
    messagingSenderId: '319505449606',
    projectId: 'mynotes-5aef6',
    authDomain: 'mynotes-5aef6.firebaseapp.com',
    storageBucket: 'mynotes-5aef6.appspot.com',
    measurementId: 'G-D9R26DZE9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfeB3FOyCYR_6QBeKbz4Y09IdWwb-l-TI',
    appId: '1:319505449606:android:d6869a739b95700e6dc707',
    messagingSenderId: '319505449606',
    projectId: 'mynotes-5aef6',
    storageBucket: 'mynotes-5aef6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0TPcc9umC-LkNLGzJ6LY1-c41H09y4bE',
    appId: '1:319505449606:ios:281d612e51536d7e6dc707',
    messagingSenderId: '319505449606',
    projectId: 'mynotes-5aef6',
    storageBucket: 'mynotes-5aef6.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );
}
