class DatabaseAlreadyOpenException implements Exception{}
class UnableToGetDocumentDirectoryException implements Exception{}
class DatabaseNotOpenException implements Exception{}
class CouldNotDeleteUser implements Exception{}
class UserAlreadyExist implements Exception{}
class CouldNotFindUser implements Exception{}
class CouldNotDeleteNote implements Exception{}
class CouldNotFindNote implements Exception{}
class CouldNotUpdateNote implements Exception{}